# Generated by Django 3.2 on 2021-04-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso_code',
            field=models.CharField(default='hk', max_length=5),
            preserve_default=False,
        ),
    ]
