# Generated by Django 3.2 on 2021-04-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelcondition',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelcondition',
            name='visit_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
