# Generated by Django 3.2 on 2021-04-16 04:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
