# Generated by Django 3.2 on 2021-04-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0002_itinerary_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='status',
            field=models.CharField(choices=[('origin', 'Origin'), ('destination', 'Destination'), ('plan', 'Plan')], default='origin', max_length=11),
        ),
    ]
