# Generated by Django 3.2 on 2021-04-16 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_city'),
        ('itinerary', '0003_itinerary_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='leaving_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='country.city'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='plan',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PastTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_date', models.DateField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='country.city')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_travels', to='country.city')),
            ],
        ),
    ]
